spring:
  security:
    oauth2:
      client:
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          google:
            clientId: "${googleclientid}"
            clientSecret: "${googleclientsecret}"
            scope: profile,email
          naver:
            clientId: "${naverclientid}"
            clientSecret: "${naverclientsecret}"
            redirectUri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorizationGrantType: authorization_code
            scope: name,email,profile_image
            clientName: Naver
          kakao:
            clientId: "${kakaoclientid}"
            clientSecret: "${kakaoclientsecret}"
            redirectUri: http://localhost:8080/login/oauth2/code/kakao
            authorizationGrantType: authorization_code
            scope: profile_image,account_email,profile_nickname
            clientName: kakao
            clientAuthenticationMethod: POST
