spring:
  profiles:
    active: local
    include: oauth
  batch:
    jdbc:
      initialize-schema: ALWAYS
    job:
      enabled: false
      names: ${job.name:NONE}
admin-key: "${kakaoAdminKey}"
kakao-base-url: https://kapi.kakao.com/v1/payment