spring:
  security:
    oauth2:
      client:
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          google:
            clientId: 152706133366-ckor721johnrir9mal9t3qdd8phnsdvj.apps.googleusercontent.com
            clientSecret: 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x
            scope: profile,email
          naver:
            clientId: tn9SUgiOQnqEees9kCdK
            clientSecret: 32qsBynot0
            redirectUri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorizationGrantType: authorization_code
            scope: name,email,profile_image
            clientName: Naver
          kakao:
            clientId: a61dfd3054779c4996aff7a1433717dd
            clientSecret: NKHmAh74yiQvwjjPIE8QLQlEJJSq4tKJ
            redirectUri: http://localhost:8080/login/oauth2/code/kakao
            authorizationGrantType: authorization_code
            scope: profile_image,account_email,profile_nickname
            clientName: kakao
            clientAuthenticationMethod: POST
